### ISSUE TITLE
Gitlab CI Integration

### ISSUE THREAD

**Issue by eemelipa** [CodSpeedHQ/runner#22]
Gitlab is one of the most popular version control / DevOps platforms used for development. Please add support for integrating CodSpeed with Gitlab.

A minimal support with some missing features would be appreciated in case providing full support requires meaningfully more effort.

**Comment by adriencaccia** [comment]
Hey, the GitLab integration is in the works!
We will update you here when it is ready 😉

**Comment by fargito** [comment]
Hello, we just released support for GitLab and GitLab CI.

You can learn more about it in [the release notes](https://codspeed.io/changelog/2024-11-26-gitlab-support).
